# from https://packaging.python.org/en/latest/appveyor/
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Uncomment this to enable building pull requests.
    - master
environment:
  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python34"
      TOXENV: "py34"
      TOXPYTHON: "%PYTHON%\\python.exe"

    - PYTHON: "C:\\Python35"
      TOXENV: "py35"
      TOXPYTHON: "%PYTHON%\\python.exe"

    - PYTHON: "C:\\Python36"
      TOXENV: "py36"
      TOXPYTHON: "%PYTHON%\\python.exe"

    - PYTHON: "C:\\Python34-x64"
      TOXENV: "py34"
      TOXPYTHON: "%PYTHON%\\python.exe"

    - PYTHON: "C:\\Python35-x64"
      TOXENV: "py35"
      TOXPYTHON: "%PYTHON%\\python.exe"

    - PYTHON: "C:\\Python36-x64"
      TOXENV: "py36"
      TOXPYTHON: "%PYTHON%\\python.exe"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install --upgrade wheel pip setuptools"
  - "py -3.5 -m pip install --upgrade wheel pip setuptools"
  - "py -3.5 -m pip install tox codecov"

build: off

test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python evrsion you want to use on PATH.
  - "py -3.5 -m tox"

# This is commented out as there's no easy way to deal with numpy dropping
# older python versions without a recent pip/setuptools.
#after_test:
#  # This step builds your wheels.
#  # Again, you only need build.cmd if you're building C extensions for
#  # 64-bit Python 3.3/3.4. And you need to use %PYTHON% to get the correct
#  # interpreter
#  - "ci\\appveyor\\build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"
#
#artifacts:
#  # bdist_wheel puts your built wheel in the dist directory
#  - path: dist\*

cache:
  - "%LOCALAPPDATA%\\pip\\Cache"

on_success:
  - "py -3.5 -m codecov"
